In [35]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
df = pd.read_csv('df_results.csv')
print(df.shape)
df.head()

(1407, 2394)

,Unnamed: 0,product_smiles,r1_label,r1_smiles,r1_smiles_raw,r3_label,r3_smiles,r3_smiles_raw,r4_label,r4_smiles,...,r5_TSRW10,r5_MW,r5_AMW,r5_WPath,r5_WPol,r5_Zagreb1,r5_Zagreb2,r5_mZagreb2,r5_type,r5_ix
0,0,CCOCN(C(C)=O)c1c(C)c(C)c(C)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,...,1.000000,16.031300,3.206260,0,0,0.0,0.0,0.0,R5,0
1,1,CCOCN(C(C)=O)c1c(C)c(C)c(C(F)(F)F)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,...,24.179697,70.003035,14.000607,9,0,12.0,9.0,1.0,R5,1
2,2,CCOCN(C(C)=O)c1c(C)c(C)c(C#N)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,...,7.493061,27.010899,9.003633,1,0,2.0,1.0,1.0,R5,2
3,3,CCOCN(C(C)=O)c1c(C)c(C)c(OC)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,...,7.493061,32.026215,5.337702,1,0,2.0,1.0,1.0,R5,3
4,4,CCOCN(C(C)=O)c1c(C)c(C)c(OC(F)(F)F)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,...,29.418928,85.997949,14.332992,16,0,20.0,16.0,1.0,R5,4

In [38]:
df['r1_label'].unique()

array(['R1_0', 'R1_1'], dtype=object)

In [39]:
df['r3_label'].unique()

array(['R3_0', 'R3_1', 'R3_2', 'R3_3', 'R3_4', 'R3_5', 'R3_6', 'R3_7'],
      dtype=object)

In [40]:
df['r4_label'].unique()

array(['R4_0', 'R4_1', 'R4_2', 'R4_3', 'R4_4', 'R4_5', 'R4_6', 'R4_7'],
      dtype=object)

In [41]:
df['r5_label'].unique()

array(['R5_0', 'R5_1', 'R5_2', 'R5_3', 'R5_4', 'R5_5', 'R5_6', 'R5_7',
       'R5_8', 'R5_9', 'R5_10'], dtype=object)

In [42]:
df.iloc[:5, :20]

,Unnamed: 0,product_smiles,r1_label,r1_smiles,r1_smiles_raw,r3_label,r3_smiles,r3_smiles_raw,r4_label,r4_smiles,r4_smiles_raw,r5_label,r5_smiles,r5_smiles_raw,ered,gsol,abs_lam,abs_lam_diff,ra_xgb,ra_nn
0,0,CCOCN(C(C)=O)c1c(C)c(C)c(C)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,C,R5_0,C,C,1.684123,-0.681801,335.04,39.96,0.927592,0.999163
1,1,CCOCN(C(C)=O)c1c(C)c(C)c(C(F)(F)F)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,C,R5_1,C(F)(F)F,C(F)(F)F,1.963624,-0.711542,311.08,63.92,0.961606,0.999867
2,2,CCOCN(C(C)=O)c1c(C)c(C)c(C#N)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,C,R5_2,C#N,C#N,2.044655,-0.887400,323.24,51.76,0.955999,0.999329
3,3,CCOCN(C(C)=O)c1c(C)c(C)c(OC)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,C,R5_3,OC,OC,1.731604,-0.710235,338.07,36.93,0.903359,0.994274
4,4,CCOCN(C(C)=O)c1c(C)c(C)c(OC(F)(F)F)c2nsnc12,R1_0,CCOC,CCOC,R3_0,C,C,R4_0,C,C,R5_4,OC(F)(F)F,OC(F)(F)F,1.844226,-0.748112,321.21,53.79,0.910281,0.799020

In [43]:
cols_olymp = ['r1_label', 'r3_label', 'r4_label', 'r5_label', 'abs_lam_diff', 'ered', 'gsol']
olymp_df = df[cols_olymp]

In [44]:
olymp_df

     r1_label r3_label r4_label r5_label  abs_lam_diff      ered      gsol
0        R1_0     R3_0     R4_0     R5_0         39.96  1.684123 -0.681801
1        R1_0     R3_0     R4_0     R5_1         63.92  1.963624 -0.711542
2        R1_0     R3_0     R4_0     R5_2         51.76  2.044655 -0.887400
3        R1_0     R3_0     R4_0     R5_3         36.93  1.731604 -0.710235
4        R1_0     R3_0     R4_0     R5_4         53.79  1.844226 -0.748112
...       ...      ...      ...      ...           ...       ...       ...
1402     R1_1     R3_7     R4_7     R5_6         28.60  1.953747 -0.645258
1403     R1_1     R3_7     R4_7     R5_7         12.22  1.921802 -0.576308
1404     R1_1     R3_7     R4_7     R5_8         25.32  1.895517 -0.614102
1405     R1_1     R3_7     R4_7     R5_9         44.07  2.129904 -0.731976
1406     R1_1     R3_7     R4_7    R5_10         27.83  2.059811 -0.928487

[1407 rows x 7 columns]

In [45]:
#olymp_df.to_csv('data.csv', index=False)

In [70]:
# load config
import json

config = json.load(open('config.json', 'r'))
config

{'constraints': {'parameters': 'none', 'measurements': 'none'},
 'parameters': [{'name': 'r1_label',
   'type': 'categorical',
   'options': ['R1_0', 'R1_1'],
   'descriptors': ['nHetero', 'MW', 'TopoPSA', 'nHeavyAtom']},
  {'name': 'r3_label',
   'type': 'categorical',
   'options': ['R3_0', 'R3_1', 'R3_2', 'R3_3', 'R3_4', 'R3_5', 'R3_6', 'R3_7'],
   'descriptors': ['nHetero',
    'MW',
    'TopoPSA',
    'nHeavyAtom',
    'apol',
    'FCSP3',
    'Diameter']},
  {'name': 'r4_label',
   'type': 'categorical',
   'options': ['R4_0', 'R4_1', 'R4_2', 'R4_3', 'R4_4', 'R4_5', 'R4_6', 'R4_7'],
   'descriptors': ['nHetero',
    'MW',
    'TopoPSA',
    'nHeavyAtom',
    'apol',
    'FCSP3',
    'Diameter']},
  {'name': 'r5_label',
   'type': 'categorical',
   'options': ['R5_0',
    'R5_1',
    'R5_2',
    'R5_3',
    'R5_4',
    'R5_5',
    'R5_6',
    'R5_7',
    'R5_8',
    'R5_9',
    'R5_10'],
   'descriptors': ['nHetero',
    'MW',
    'TopoPSA',
    'nHeavyAtom',
    'apol',
    'FCSP3',
    'Diameter']}],
 'measurements': [{'name': 'abs_lam_diff', 'type': 'continuous'},
  {'name': 'ered', 'type': 'continuous'},
  {'name': 'gsol', 'type': 'continuous'}],
 'default_goal': ['minimize', 'minimize', 'minimize']}

In [76]:
# make the descriptors df
desc_dict = {'variable_name': [], 'option_name': [], 'descriptor_name': [], 'descriptor_value': []}


# group_type=variable_name,  lookup_label=option_name, desc=descriptor_name
def get_descriptors(group_type, lookup_label, desc_name):
    """ returns list of descriptor values for a given
    list of descriptor types
    """
    desc_vals = []
    val = df[df[f'{group_type}']==lookup_label][f'{group_type.split("_")[0]}_{desc_name}'].tolist()[0]
    return val



variable_names = [v['name'] for v in config['parameters']]
option_names   = [v['options'] for v in config['parameters']]
descriptor_names = [v['descriptors'] for v in config['parameters']]

In [77]:
for variable_idx, variable_name in enumerate(variable_names):
    for option_name in option_names[variable_idx]:
        for descriptor_name in descriptor_names[variable_idx]:
            print(variable_name, option_name, descriptor_name)
            val = get_descriptors(variable_name, option_name, descriptor_name)
            
            desc_dict['variable_name'].append(variable_name)
            desc_dict['option_name'].append(option_name)
            desc_dict['descriptor_name'].append(descriptor_name)
            desc_dict['descriptor_value'].append(val)

r1_label R1_0 nHetero
r1_label R1_0 MW
r1_label R1_0 TopoPSA
r1_label R1_0 nHeavyAtom
r1_label R1_1 nHetero
r1_label R1_1 MW
r1_label R1_1 TopoPSA
r1_label R1_1 nHeavyAtom
r3_label R3_0 nHetero
r3_label R3_0 MW
r3_label R3_0 TopoPSA
r3_label R3_0 nHeavyAtom
r3_label R3_0 apol
r3_label R3_0 FCSP3
r3_label R3_0 Diameter
r3_label R3_1 nHetero
r3_label R3_1 MW
r3_label R3_1 TopoPSA
r3_label R3_1 nHeavyAtom
r3_label R3_1 apol
r3_label R3_1 FCSP3
r3_label R3_1 Diameter
r3_label R3_2 nHetero
r3_label R3_2 MW
r3_label R3_2 TopoPSA
r3_label R3_2 nHeavyAtom
r3_label R3_2 apol
r3_label R3_2 FCSP3
r3_label R3_2 Diameter
r3_label R3_3 nHetero
r3_label R3_3 MW
r3_label R3_3 TopoPSA
r3_label R3_3 nHeavyAtom
r3_label R3_3 apol
r3_label R3_3 FCSP3
r3_label R3_3 Diameter
r3_label R3_4 nHetero
r3_label R3_4 MW
r3_label R3_4 TopoPSA
r3_label R3_4 nHeavyAtom
r3_label R3_4 apol
r3_label R3_4 FCSP3
r3_label R3_4 Diameter
r3_label R3_5 nHetero
r3_label R3_5 MW
r3_label R3_5 TopoPSA
r3_label R3_5 nHeavyAtom
r3_label R3_5 apol
r3_label R3_5 FCSP3
r3_label R3_5 Diameter
r3_label R3_6 nHetero
r3_label R3_6 MW
r3_label R3_6 TopoPSA
r3_label R3_6 nHeavyAtom
r3_label R3_6 apol
r3_label R3_6 FCSP3
r3_label R3_6 Diameter
r3_label R3_7 nHetero
r3_label R3_7 MW
r3_label R3_7 TopoPSA
r3_label R3_7 nHeavyAtom
r3_label R3_7 apol
r3_label R3_7 FCSP3
r3_label R3_7 Diameter
r4_label R4_0 nHetero
r4_label R4_0 MW
r4_label R4_0 TopoPSA
r4_label R4_0 nHeavyAtom
r4_label R4_0 apol
r4_label R4_0 FCSP3
r4_label R4_0 Diameter
r4_label R4_1 nHetero
r4_label R4_1 MW
r4_label R4_1 TopoPSA
r4_label R4_1 nHeavyAtom
r4_label R4_1 apol
r4_label R4_1 FCSP3
r4_label R4_1 Diameter
r4_label R4_2 nHetero
r4_label R4_2 MW
r4_label R4_2 TopoPSA
r4_label R4_2 nHeavyAtom
r4_label R4_2 apol
r4_label R4_2 FCSP3
r4_label R4_2 Diameter
r4_label R4_3 nHetero
r4_label R4_3 MW
r4_label R4_3 TopoPSA
r4_label R4_3 nHeavyAtom
r4_label R4_3 apol
r4_label R4_3 FCSP3
r4_label R4_3 Diameter
r4_label R4_4 nHetero
r4_label R4_4 MW
r4_label R4_4 TopoPSA
r4_label R4_4 nHeavyAtom
r4_label R4_4 apol
r4_label R4_4 FCSP3
r4_label R4_4 Diameter
r4_label R4_5 nHetero
r4_label R4_5 MW
r4_label R4_5 TopoPSA
r4_label R4_5 nHeavyAtom
r4_label R4_5 apol
r4_label R4_5 FCSP3
r4_label R4_5 Diameter
r4_label R4_6 nHetero
r4_label R4_6 MW
r4_label R4_6 TopoPSA
r4_label R4_6 nHeavyAtom
r4_label R4_6 apol
r4_label R4_6 FCSP3
r4_label R4_6 Diameter
r4_label R4_7 nHetero
r4_label R4_7 MW
r4_label R4_7 TopoPSA
r4_label R4_7 nHeavyAtom
r4_label R4_7 apol
r4_label R4_7 FCSP3
r4_label R4_7 Diameter
r5_label R5_0 nHetero
r5_label R5_0 MW
r5_label R5_0 TopoPSA
r5_label R5_0 nHeavyAtom
r5_label R5_0 apol
r5_label R5_0 FCSP3
r5_label R5_0 Diameter
r5_label R5_1 nHetero
r5_label R5_1 MW
r5_label R5_1 TopoPSA
r5_label R5_1 nHeavyAtom
r5_label R5_1 apol
r5_label R5_1 FCSP3
r5_label R5_1 Diameter
r5_label R5_2 nHetero
r5_label R5_2 MW
r5_label R5_2 TopoPSA
r5_label R5_2 nHeavyAtom
r5_label R5_2 apol
r5_label R5_2 FCSP3
r5_label R5_2 Diameter
r5_label R5_3 nHetero
r5_label R5_3 MW
r5_label R5_3 TopoPSA
r5_label R5_3 nHeavyAtom
r5_label R5_3 apol
r5_label R5_3 FCSP3
r5_label R5_3 Diameter
r5_label R5_4 nHetero
r5_label R5_4 MW
r5_label R5_4 TopoPSA
r5_label R5_4 nHeavyAtom
r5_label R5_4 apol
r5_label R5_4 FCSP3
r5_label R5_4 Diameter
r5_label R5_5 nHetero
r5_label R5_5 MW
r5_label R5_5 TopoPSA
r5_label R5_5 nHeavyAtom
r5_label R5_5 apol
r5_label R5_5 FCSP3
r5_label R5_5 Diameter
r5_label R5_6 nHetero
r5_label R5_6 MW
r5_label R5_6 TopoPSA
r5_label R5_6 nHeavyAtom
r5_label R5_6 apol
r5_label R5_6 FCSP3
r5_label R5_6 Diameter
r5_label R5_7 nHetero
r5_label R5_7 MW
r5_label R5_7 TopoPSA
r5_label R5_7 nHeavyAtom
r5_label R5_7 apol
r5_label R5_7 FCSP3
r5_label R5_7 Diameter
r5_label R5_8 nHetero
r5_label R5_8 MW
r5_label R5_8 TopoPSA
r5_label R5_8 nHeavyAtom
r5_label R5_8 apol
r5_label R5_8 FCSP3
r5_label R5_8 Diameter
r5_label R5_9 nHetero
r5_label R5_9 MW
r5_label R5_9 TopoPSA
r5_label R5_9 nHeavyAtom
r5_label R5_9 apol
r5_label R5_9 FCSP3
r5_label R5_9 Diameter
r5_label R5_10 nHetero
r5_label R5_10 MW
r5_label R5_10 TopoPSA
r5_label R5_10 nHeavyAtom
r5_label R5_10 apol
r5_label R5_10 FCSP3
r5_label R5_10 Diameter

In [78]:
desc_df = pd.DataFrame(desc_dict)
print(desc_df.shape)
desc_df.head()

(197, 4)

  variable_name option_name descriptor_name  descriptor_value
0      r1_label        R1_0         nHetero          1.000000
1      r1_label        R1_0              MW         60.057515
2      r1_label        R1_0         TopoPSA          9.230000
3      r1_label        R1_0      nHeavyAtom          4.000000
4      r1_label        R1_1         nHetero          5.000000

In [80]:
desc_df.to_csv('descriptors.csv', index=)

197